"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

import { StatusPill } from "@/components/ui/status-pill";
import { apiRequest } from "@/lib/api";
import type {
  CreatePaymentPayload,
  CreatePaymentResponseData,
  Payment,
  PaymentMethod,
  PaymentStatus,
  PaymentSubscription,
  PaymentSummaryResponseData,
  PaymentsResponseData,
  SubscriptionsResponseData,
} from "@/lib/types";

function formatMoney(value: number) {
  return new Intl.NumberFormat("en-ZA", {
    style: "currency",
    currency: "ZAR",
    maximumFractionDigits: 0,
  }).format(value || 0);
}

function getMemberName(member?: { firstName?: string; lastName?: string }) {
  if (!member) return "Unknown member";
  return `${member.firstName || ""} ${member.lastName || ""}`.trim();
}

function normalizeText(value: unknown) {
  return String(value || "").toLowerCase();
}

function formatDateTime(value?: string) {
  if (!value) return "—";

  return new Intl.DateTimeFormat("en-ZA", {
    day: "2-digit",
    month: "short",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(value));
}

function formatDate(value?: string) {
  if (!value) return "—";

  return new Intl.DateTimeFormat("en-ZA", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  }).format(new Date(value));
}

function MiniMetric({
  label,
  value,
  helper,
}: {
  label: string;
  value: string | number;
  helper: string;
}) {
  return (
    <div className="rounded-[2.2rem] bg-white/55 px-5 py-4 shadow-sm ring-1 ring-black/5">
      <p className="text-[11px] uppercase tracking-[0.18em] text-zinc-500">
        {label}
      </p>
      <p className="mt-2 text-[22px] font-medium tracking-[-0.04em] text-zinc-950">
        {value}
      </p>
      <p className="mt-1 text-[12px] text-zinc-500">{helper}</p>
    </div>
  );
}

const inputClass =
  "h-11 w-full rounded-2xl border-0 bg-white px-4 text-[13px] text-zinc-800 shadow-sm ring-1 ring-black/5 outline-none transition placeholder:text-zinc-400 focus:ring-2 focus:ring-[#e8ff5f]";

const selectClass =
  "h-11 w-full appearance-none rounded-2xl border-0 bg-white px-4 text-[13px] text-zinc-800 shadow-sm ring-1 ring-black/5 outline-none transition focus:ring-2 focus:ring-[#e8ff5f]";

const textareaClass =
  "min-h-24 w-full resize-none rounded-2xl border-0 bg-white px-4 py-3 text-[13px] text-zinc-800 shadow-sm ring-1 ring-black/5 outline-none transition placeholder:text-zinc-400 focus:ring-2 focus:ring-[#e8ff5f]";

function PaymentTable({ payments }: { payments: Payment[] }) {
  return (
    <div className="overflow-x-auto rounded-[1.4rem] bg-[#f4f4f2]">
      <table className="min-w-full border-collapse">
        <thead>
          <tr className="bg-[#dededb] text-left">
            <th className="px-5 py-4 text-[12px] font-medium text-zinc-600">
              Receipt / Reference
            </th>
            <th className="px-5 py-4 text-[12px] font-medium text-zinc-600">
              Member
            </th>
            <th className="px-5 py-4 text-[12px] font-medium text-zinc-600">
              Plan
            </th>
            <th className="px-5 py-4 text-[12px] font-medium text-zinc-600">
              Amount
            </th>
            <th className="px-5 py-4 text-[12px] font-medium text-zinc-600">
              Method
            </th>
            <th className="px-5 py-4 text-[12px] font-medium text-zinc-600">
              Status
            </th>
            <th className="px-5 py-4 text-[12px] font-medium text-zinc-600">
              Paid at
            </th>
          </tr>
        </thead>

        <tbody>
          {payments.length === 0 ? (
            <tr>
              <td
                colSpan={7}
                className="px-5 py-14 text-center text-[13px] text-zinc-500"
              >
                No payments found.
              </td>
            </tr>
          ) : (
            payments.map((payment) => (
              <tr
                key={payment._id}
                className="border-b border-black/10 last:border-0"
              >
                <td className="px-5 py-4">
                  <p className="text-[13px] font-medium text-zinc-950">
                    {payment.receiptNumber}
                  </p>
                  <p className="mt-1 max-w-[260px] truncate text-[12px] text-zinc-500">
                    {payment.reference || "Reference generated by system"}
                  </p>
                </td>

                <td className="px-5 py-4">
                  <p className="text-[13px] font-medium text-zinc-950">
                    {getMemberName(payment.member)}
                  </p>
                  <p className="mt-1 text-[12px] text-zinc-500">
                    {payment.member?.memberCode || "—"}
                  </p>
                </td>

                <td className="px-5 py-4 text-[13px] text-zinc-700">
                  {payment.subscription?.planSnapshot?.name || "—"}
                </td>

                <td className="px-5 py-4 text-[13px] font-medium text-zinc-950">
                  {formatMoney(payment.amount)}
                </td>

                <td className="px-5 py-4 text-[13px] capitalize text-zinc-700">
                  {payment.method.replace("_", " ")}
                </td>

                <td className="px-5 py-4">
                  <StatusPill status={payment.status} />
                </td>

                <td className="px-5 py-4 text-[13px] text-zinc-700">
                  {formatDateTime(payment.paidAt || payment.createdAt)}
                </td>
              </tr>
            ))
          )}
        </tbody>
      </table>
    </div>
  );
}

function SubscriptionOptionLabel({
  subscription,
}: {
  subscription: PaymentSubscription;
}) {
  const member = subscription.member;
  const balance =
    subscription.planSnapshot.price -
    (subscription.paymentStatus === "paid"
      ? subscription.planSnapshot.price
      : 0);

  return (
    <div>
      <p className="text-[13px] font-medium text-zinc-950">
        {getMemberName(member)} · {subscription.planSnapshot.name}
      </p>
      <p className="mt-1 text-[12px] text-zinc-500">
        {member?.memberCode || "No code"} · {subscription.paymentStatus} ·{" "}
        {formatMoney(Math.max(balance, 0))}
      </p>
    </div>
  );
}

export default function PaymentsPage() {
  const [payments, setPayments] = useState<Payment[]>([]);
  const [subscriptions, setSubscriptions] = useState<PaymentSubscription[]>([]);
  const [summary, setSummary] = useState<PaymentSummaryResponseData | null>(
    null,
  );

  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<"all" | PaymentStatus>(
    "all",
  );
  const [methodFilter, setMethodFilter] = useState<"all" | PaymentMethod>(
    "all",
  );

  const [selectedSubscriptionId, setSelectedSubscriptionId] = useState("");
  const [amount, setAmount] = useState("");
  const [method, setMethod] = useState<PaymentMethod>("cash");
  const [status, setStatus] = useState<PaymentStatus>("paid");
  const [notes, setNotes] = useState("");

  const [error, setError] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const loadPaymentData = useCallback(async () => {
    try {
      const [paymentsResponse, summaryResponse, subscriptionsResponse] =
        await Promise.all([
          apiRequest<PaymentsResponseData>("/payments?limit=100"),
          apiRequest<PaymentSummaryResponseData>("/payments/summary"),
          apiRequest<SubscriptionsResponseData>("/subscriptions?limit=100"),
        ]);

      setPayments(paymentsResponse.data?.payments || []);
      setSummary(summaryResponse.data || null);
      setSubscriptions(subscriptionsResponse.data?.subscriptions || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load payments.");
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      void loadPaymentData();
    }, 0);

    return () => {
      window.clearTimeout(timer);
    };
  }, [loadPaymentData]);

  const payableSubscriptions = useMemo(() => {
    return subscriptions.filter((subscription) => {
      const isUsableStatus = !["cancelled", "suspended"].includes(
        subscription.status,
      );

      const isNotFullyPaid = subscription.paymentStatus !== "paid";

      return isUsableStatus && isNotFullyPaid;
    });
  }, [subscriptions]);

  const selectedSubscription = useMemo(() => {
    return subscriptions.find(
      (subscription) => subscription._id === selectedSubscriptionId,
    );
  }, [subscriptions, selectedSubscriptionId]);

  const suggestedAmount = useMemo(() => {
    if (!selectedSubscription) return 0;

    if (selectedSubscription.paymentStatus === "paid") return 0;

    return selectedSubscription.planSnapshot.price;
  }, [selectedSubscription]);

  const filteredPayments = useMemo(() => {
    return payments.filter((payment) => {
      const searchable = [
        payment.receiptNumber,
        payment.reference,
        payment.method,
        payment.status,
        getMemberName(payment.member),
        payment.member?.memberCode,
        payment.member?.phone,
        payment.subscription?.planSnapshot?.name,
      ].join(" ");

      const matchesSearch = normalizeText(searchable).includes(
        normalizeText(searchQuery),
      );

      const matchesStatus =
        statusFilter === "all" || payment.status === statusFilter;

      const matchesMethod =
        methodFilter === "all" || payment.method === methodFilter;

      return matchesSearch && matchesStatus && matchesMethod;
    });
  }, [payments, searchQuery, statusFilter, methodFilter]);

  const pendingPayments = payments.filter(
    (payment) => payment.status === "pending",
  );

  async function handleCreatePayment(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    setError("");
    setSuccessMessage("");

    if (!selectedSubscriptionId) {
      setError("Select a subscription before recording payment.");
      return;
    }

    const numericAmount = Number(amount);

    if (!numericAmount || numericAmount <= 0) {
      setError("Enter a valid payment amount.");
      return;
    }

    setIsSubmitting(true);

    try {
      const payload: CreatePaymentPayload = {
        subscriptionId: selectedSubscriptionId,
        amount: numericAmount,
        method,
        status,
        notes: notes || undefined,
      };

      const response = await apiRequest<CreatePaymentResponseData>(
        "/payments",
        {
          method: "POST",
          body: payload,
        },
      );

      setSuccessMessage(response.message || "Payment recorded successfully.");

      setSelectedSubscriptionId("");
      setAmount("");
      setMethod("cash");
      setStatus("paid");
      setNotes("");

      await loadPaymentData();
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to record payment.",
      );
    } finally {
      setIsSubmitting(false);
    }
  }

  function handleSubscriptionChange(subscriptionId: string) {
    setSelectedSubscriptionId(subscriptionId);

    const subscription = subscriptions.find(
      (item) => item._id === subscriptionId,
    );

    if (subscription && subscription.paymentStatus !== "paid") {
      setAmount(String(subscription.planSnapshot.price));
    }
  }

  if (isLoading) {
    return (
      <div className="rounded-[1.7rem] bg-white/55 p-8 text-[13px] text-zinc-500 shadow-sm ring-1 ring-black/5">
        Loading payments...
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <section className="grid gap-3 lg:grid-cols-4">
        <MiniMetric
          label="Today"
          value={formatMoney(summary?.today.totalRevenue || 0)}
          helper={`${summary?.today.totalPayments || 0} payment(s)`}
        />
        <MiniMetric
          label="This week"
          value={formatMoney(summary?.week.totalRevenue || 0)}
          helper={`${summary?.week.totalPayments || 0} payment(s)`}
        />
        <MiniMetric
          label="This month"
          value={formatMoney(summary?.month.totalRevenue || 0)}
          helper={`${summary?.month.totalPayments || 0} payment(s)`}
        />
        <MiniMetric
          label="Pending"
          value={pendingPayments.length}
          helper="Payments awaiting confirmation"
        />
      </section>

      <section className="rounded-[1.7rem] bg-white/55 p-4 shadow-sm ring-1 ring-black/5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <p className="text-[11px] uppercase tracking-[0.2em] text-zinc-500">
              Payments
            </p>
            <h2 className="mt-1 text-[28px] font-medium tracking-[-0.04em] text-zinc-950">
              Payment Management
            </h2>
            <p className="mt-1 text-[13px] text-zinc-500">
              Record gym payments, confirm EFTs, and track revenue.
            </p>
          </div>

          <button
            onClick={loadPaymentData}
            className="h-10 rounded-full bg-white px-5 text-[13px] text-zinc-700 shadow-sm ring-1 ring-black/5 transition hover:bg-zinc-950 hover:text-white"
          >
            Refresh
          </button>
        </div>
      </section>

      <section className="grid gap-4 xl:grid-cols-[440px_1fr]">
        <form
          onSubmit={handleCreatePayment}
          className="space-y-4 rounded-[1.7rem] bg-white/60 p-4 shadow-sm ring-1 ring-black/5"
        >
          <div>
            <h3 className="text-[16px] font-medium text-zinc-950">
              Record payment
            </h3>
            <p className="mt-1 text-[13px] text-zinc-500">
              Select an unpaid or partial subscription and record the payment.
            </p>
          </div>

          <label className="space-y-2">
            <span className="block text-[12px] font-medium text-zinc-600">
              Subscription
            </span>

            <select
              value={selectedSubscriptionId}
              onChange={(event) => handleSubscriptionChange(event.target.value)}
              className={selectClass}
            >
              <option value="">Select subscription</option>
              {payableSubscriptions.map((subscription) => (
                <option key={subscription._id} value={subscription._id}>
                  {getMemberName(subscription.member)} ·{" "}
                  {subscription.planSnapshot.name} ·{" "}
                  {formatMoney(subscription.planSnapshot.price)} ·{" "}
                  {subscription.paymentStatus}
                </option>
              ))}
            </select>
          </label>

          {selectedSubscription ? (
            <div className="rounded-[1.3rem] bg-[#f4f4f2] p-4 ring-1 ring-black/5">
              <SubscriptionOptionLabel subscription={selectedSubscription} />

              <div className="mt-4 grid grid-cols-2 gap-3">
                <div>
                  <p className="text-[12px] text-zinc-500">Plan price</p>
                  <p className="mt-1 text-[15px] font-medium text-zinc-950">
                    {formatMoney(selectedSubscription.planSnapshot.price)}
                  </p>
                </div>

                <div>
                  <p className="text-[12px] text-zinc-500">Ends</p>
                  <p className="mt-1 text-[15px] font-medium text-zinc-950">
                    {formatDate(selectedSubscription.endsAt)}
                  </p>
                </div>
              </div>
            </div>
          ) : null}

          <label className="space-y-2">
            <span className="block text-[12px] font-medium text-zinc-600">
              Amount
            </span>
            <input
              value={amount}
              onChange={(event) => setAmount(event.target.value)}
              className={inputClass}
              placeholder={suggestedAmount ? String(suggestedAmount) : "350"}
              inputMode="decimal"
            />
          </label>

          <div className="grid gap-3 md:grid-cols-2">
            <label className="space-y-2">
              <span className="block text-[12px] font-medium text-zinc-600">
                Method
              </span>
              <select
                value={method}
                onChange={(event) =>
                  setMethod(event.target.value as PaymentMethod)
                }
                className={selectClass}
              >
                <option value="cash">Cash</option>
                <option value="card">Card</option>
                <option value="eft">EFT</option>
                <option value="bank_transfer">Bank transfer</option>
                <option value="other">Other</option>
              </select>
            </label>

            <label className="space-y-2">
              <span className="block text-[12px] font-medium text-zinc-600">
                Status
              </span>
              <select
                value={status}
                onChange={(event) =>
                  setStatus(event.target.value as PaymentStatus)
                }
                className={selectClass}
              >
                <option value="paid">Paid</option>
                <option value="pending">Pending</option>
                <option value="failed">Failed</option>
                <option value="refunded">Refunded</option>
              </select>
            </label>
          </div>

          <div className="rounded-[1.3rem] bg-[#f4f4f2] p-4 text-[13px] leading-6 text-zinc-600 ring-1 ring-black/5">
            Payment references are generated automatically by the system using
            the member name, member code, and payment date.
          </div>

          <label className="space-y-2">
            <span className="block text-[12px] font-medium text-zinc-600">
              Notes optional
            </span>
            <textarea
              value={notes}
              onChange={(event) => setNotes(event.target.value)}
              className={textareaClass}
              placeholder="Cash received at reception, EFT awaiting confirmation, etc."
            />
          </label>

          {error ? (
            <div className="rounded-[1.3rem] bg-red-50 p-4 text-[13px] text-red-700 ring-1 ring-red-200">
              {error}
            </div>
          ) : null}

          {successMessage ? (
            <div className="rounded-[1.3rem] bg-emerald-50 p-4 text-[13px] text-emerald-700 ring-1 ring-emerald-200">
              {successMessage}
            </div>
          ) : null}

          <button
            type="submit"
            disabled={isSubmitting}
            className="h-12 w-full rounded-full bg-[#e8ff5f] text-[13px] font-medium text-zinc-950 shadow-sm ring-1 ring-black/5 transition hover:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-60"
          >
            {isSubmitting ? "Recording payment..." : "Record payment"}
          </button>
        </form>

        <div className="space-y-4">
          <section className="rounded-[1.7rem] bg-white/55 p-3 shadow-sm ring-1 ring-black/5">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <label className="relative h-10 w-[320px] max-w-full">
                <span className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-[13px] text-zinc-500">
                  ⌕
                </span>
                <input
                  value={searchQuery}
                  onChange={(event) => setSearchQuery(event.target.value)}
                  placeholder="Search receipt, member, phone, reference..."
                  className="h-full w-full rounded-2xl border-0 bg-white pl-9 pr-4 text-[13px] text-zinc-800 shadow-sm ring-1 ring-black/5 outline-none transition placeholder:text-zinc-400 focus:ring-2 focus:ring-[#e8ff5f]"
                />
              </label>

              <div className="flex flex-wrap gap-2">
                <select
                  value={statusFilter}
                  onChange={(event) =>
                    setStatusFilter(event.target.value as "all" | PaymentStatus)
                  }
                  className="h-10 appearance-none rounded-2xl border-0 bg-white px-4 text-[13px] text-zinc-700 shadow-sm ring-1 ring-black/5 outline-none focus:ring-2 focus:ring-[#e8ff5f]"
                >
                  <option value="all">All statuses</option>
                  <option value="paid">Paid</option>
                  <option value="pending">Pending</option>
                  <option value="failed">Failed</option>
                  <option value="refunded">Refunded</option>
                </select>

                <select
                  value={methodFilter}
                  onChange={(event) =>
                    setMethodFilter(event.target.value as "all" | PaymentMethod)
                  }
                  className="h-10 appearance-none rounded-2xl border-0 bg-white px-4 text-[13px] text-zinc-700 shadow-sm ring-1 ring-black/5 outline-none focus:ring-2 focus:ring-[#e8ff5f]"
                >
                  <option value="all">All methods</option>
                  <option value="cash">Cash</option>
                  <option value="card">Card</option>
                  <option value="eft">EFT</option>
                  <option value="bank_transfer">Bank transfer</option>
                  <option value="other">Other</option>
                </select>
              </div>
            </div>
          </section>

          <section className="overflow-hidden rounded-[1.7rem] bg-white/70 p-3 shadow-sm ring-1 ring-black/5">
            <div className="mb-3 flex items-center justify-between px-1">
              <p className="text-[13px] font-medium text-zinc-950">
                Payment records
              </p>
              <p className="text-[12px] text-zinc-500">
                {filteredPayments.length} record(s)
              </p>
            </div>

            <PaymentTable payments={filteredPayments} />
          </section>
        </div>
      </section>
    </div>
  );
}
